In [8]:
import pandas as pd
import numpy as np

In [10]:
#creating a dataframe
elclasico = [["Messi", "Barcelona", "Striker", 10], ["Ronaldo", "Juventus", "Striker", 7], ["Mo Sallah", "Liverpool", "Striker", 10],  ["Kante", "Chelsea", "Midfielder", 7], ["Hazard", "Real Madrid", "Midfielder", 10],  ["Iheanacho", "Leicester", "striker", 14 ], ["Indidi", "Leicester","Midfielder", 25],  ["Kane", "Tottenham", "Midfeilder", 10],["Pogba", "Mancester United", "Midfeilder", 6], ["Rashford", "Manchester United", "Midfeilder", 10]]  

In [43]:
#assigning names to the columns
Football= pd.DataFrame(elclasico, columns = ["Player", "Club", "Position", "Jersey No"])
Football

Player               Club    Position  Jersey No
0      Messi          Barcelona     Striker         10
1    Ronaldo           Juventus     Striker          7
2  Mo Sallah          Liverpool     Striker         10
3      Kante            Chelsea  Midfielder          7
4     Hazard        Real Madrid  Midfielder         10
5  Iheanacho          Leicester     striker         14
6     Indidi          Leicester  Midfielder         25
7       Kane          Tottenham  Midfeilder         10
8      Pogba   Mancester United  Midfeilder          6
9   Rashford  Manchester United  Midfeilder         10

**Extract the first five rows**

In [28]:
#using the loc method
Football.loc["1st":"5th"]

Player         Club    Position  Jersey No
1st      Messi    Barcelona     Striker         10
2nd    Ronaldo     Juventus     Striker          7
3rd  Mo Sallah    Liverpool     Striker         10
4th      Kante      Chelsea  Midfielder          7
5th     Hazard  Real Madrid  Midfielder         10

In [30]:
#using iloc method
Football.iloc[0:5]

Player         Club    Position  Jersey No
1st      Messi    Barcelona     Striker         10
2nd    Ronaldo     Juventus     Striker          7
3rd  Mo Sallah    Liverpool     Striker         10
4th      Kante      Chelsea  Midfielder          7
5th     Hazard  Real Madrid  Midfielder         10

In [39]:
Football = pd.DataFrame({"Player":["Messi","Ronaldo","Mo Sallah","Kante","Hazard","Iheanacho","Indidi","Kane","Pogba","Rashford"]})
Football.columns = ["Footballer"]
Football

Footballer
0      Messi
1    Ronaldo
2  Mo Sallah
3      Kante
4     Hazard
5  Iheanacho
6     Indidi
7       Kane
8      Pogba
9   Rashford

In [44]:
#renaming columns
Football2 = Football.rename(columns = {"Club":"CN"})
Football2

Player                 CN    Position  Jersey No
0      Messi          Barcelona     Striker         10
1    Ronaldo           Juventus     Striker          7
2  Mo Sallah          Liverpool     Striker         10
3      Kante            Chelsea  Midfielder          7
4     Hazard        Real Madrid  Midfielder         10
5  Iheanacho          Leicester     striker         14
6     Indidi          Leicester  Midfielder         25
7       Kane          Tottenham  Midfeilder         10
8      Pogba   Mancester United  Midfeilder          6
9   Rashford  Manchester United  Midfeilder         10

In [38]:
#converting column with integer to float
Football_New = Football["Jersey No" ] = Football ["Jersey No"].astype(float)
print(Football_New)

0    10.0
1     7.0
2    10.0
3     7.0
4    10.0
5    14.0
6    25.0
7    10.0
8     6.0
9    10.0
Name: Jersey No, dtype: float64


In [41]:
#identifying cell content using iloc method
Football.iloc[2,1]

'Liverpool'

In [40]:
#Renaming row index
Football= pd.DataFrame(elclasico, columns = ["Player", "Club", "Position", "Jersey No"])
Football
Football.index = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th"]
Football

Player               Club    Position  Jersey No
1st       Messi          Barcelona     Striker         10
2nd     Ronaldo           Juventus     Striker          7
3rd   Mo Sallah          Liverpool     Striker         10
4th       Kante            Chelsea  Midfielder          7
5th      Hazard        Real Madrid  Midfielder         10
6th   Iheanacho          Leicester     striker         14
7th      Indidi          Leicester  Midfielder         25
8th        Kane          Tottenham  Midfeilder         10
9th       Pogba   Mancester United  Midfeilder          6
10th   Rashford  Manchester United  Midfeilder         10

In [42]:
#Resetting index
Football.reset_index(inplace=True,drop =True)
print(Football)

      Player               Club    Position  Jersey No
0      Messi          Barcelona     Striker         10
1    Ronaldo           Juventus     Striker          7
2  Mo Sallah          Liverpool     Striker         10
3      Kante            Chelsea  Midfielder          7
4     Hazard        Real Madrid  Midfielder         10
5  Iheanacho          Leicester     striker         14
6     Indidi          Leicester  Midfielder         25
7       Kane          Tottenham  Midfeilder         10
8      Pogba   Mancester United  Midfeilder          6
9   Rashford  Manchester United  Midfeilder         10


In [14]:
#creating a two dimentional array
twoDim =np.array ([[10, 8, 6, 4], [20, 18, 16, 14], [12, 9, 7, 3]])
print(f"The shape of the array is, {twoDim.shape}\n")
twoDim

The shape of the array is, (3, 4)



array([[10,  8,  6,  4],
       [20, 18, 16, 14],
       [12,  9,  7,  3]])

In [15]:
#Transposing an array
arrayTranspose = twoDim.T
print(arrayTranspose.shape)

(4, 3)


In [36]:
randArray = np.random.rand(4,3)
randArray

array([[0.16084859, 0.54175891, 0.98098929],
       [0.52552263, 0.29395511, 0.13281397],
       [0.61425161, 0.50717884, 0.51999787],
       [0.62913577, 0.35111614, 0.59675117]])

In [37]:
#multiplying array1 and array2
array1 = twoDim
array2 = randArray

print(array1)
print(array2)


[[10  8  6  4]
 [20 18 16 14]
 [12  9  7  3]]
[[0.16084859 0.54175891 0.98098929]
 [0.52552263 0.29395511 0.13281397]
 [0.61425161 0.50717884 0.51999787]
 [0.62913577 0.35111614 0.59675117]]


In [38]:
array1.dot(array2)

array([[12.01471966, 12.2167675 , 16.37939663],
       [31.31230562, 29.15685741, 38.68491971],
       [12.84705531, 13.75030311, 18.39743589]])